
package com.victor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerPort", targetNamespace = "http://victor.com.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerPort {


    /**
     * 
     * @param getCustomerDetailRequest
     * @return
     *     returns com.victor.GetCustomerDetailResponse
     */
    @WebMethod(operationName = "GetCustomerDetail")
    @WebResult(name = "GetCustomerDetailResponse", targetNamespace = "http://victor.com.br", partName = "GetCustomerDetailResponse")
    public GetCustomerDetailResponse getCustomerDetail(
        @WebParam(name = "GetCustomerDetailRequest", targetNamespace = "http://victor.com.br", partName = "GetCustomerDetailRequest")
        GetCustomerDetailRequest getCustomerDetailRequest);

    /**
     * 
     * @param getAllCustomerDetailRequest
     * @return
     *     returns com.victor.GetAllCustomerDetailResponse
     */
    @WebMethod(operationName = "GetAllCustomerDetail")
    @WebResult(name = "GetAllCustomerDetailResponse", targetNamespace = "http://victor.com.br", partName = "GetAllCustomerDetailResponse")
    public GetAllCustomerDetailResponse getAllCustomerDetail(
        @WebParam(name = "GetAllCustomerDetailRequest", targetNamespace = "http://victor.com.br", partName = "GetAllCustomerDetailRequest")
        GetAllCustomerDetailRequest getAllCustomerDetailRequest);

    /**
     * 
     * @param removeCustomerDetailRequest
     * @return
     *     returns com.victor.RemoveCustomerDetailResponse
     */
    @WebMethod(operationName = "RemoveCustomerDetail")
    @WebResult(name = "RemoveCustomerDetailResponse", targetNamespace = "http://victor.com.br", partName = "RemoveCustomerDetailResponse")
    public RemoveCustomerDetailResponse removeCustomerDetail(
        @WebParam(name = "RemoveCustomerDetailRequest", targetNamespace = "http://victor.com.br", partName = "RemoveCustomerDetailRequest")
        RemoveCustomerDetailRequest removeCustomerDetailRequest);

}
